name: Go Backend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Testing Secrets
        run: echo "DEVOPS_SECRET=${{ secrets.SECRETS_TOKEN }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0' 

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-go-mod-cache

      - name: Install Dependencies
        run: go mod tidy  # Dependencies cleanup

      - name: Build Backend
        run: go build -o backend-api main.go  # Binary build

      - name: Run Unit & API Tests
        run: go test ./... -v  # Unit tests and API tests

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: /tmp/test-reports  # Test logs path

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend-api
